my_string = (input())
stringLength = len(my_string)
print (stringLength)
print (my_string.upper())
print (my_string.lower())
print (my_string.replace(' ',''))
print (my_string[:1])
print (my_string[:stringLength-2:-1])